version: "3.8"
services:
  frontend:
    build:
      context: ./watch_together_fe
    env_file: "./watch_together_fe/.env"
    ports:
      - "4173:4173"

  backend:
    build:
      context: ./watch_together_be
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    env_file: "postgres.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
