version: "3.8"
services:
  frontend:
    build:
      context: ./watch_together_fe
    env_file: "./watch_together_fe/.env"
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production # Set any necessary environment variables here

  backend:
    build:
      context: ./watch_together_be
    env_file: "./watch_together_be/config/.production.env"
    ports:
      - "3000:3000" # Map port 3000 on the host to port 80 in the container
    environment:
      - NODE_ENV=production # Set any necessary environment variables here
    depends_on:
      - db

  db:
    image: postgres:15-alpine # Use a specific version of Postgres
    env_file: "postgres.env"
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
